Fixes failing test on macOS, preventing install
rurban/b-keywords pull request #5
Opened 2021-11-22 07:26 UTC by nega0

Test `11keywords.t` fails on recent versions of macOS due to Apple
relocating files. This commit test's for `darwin` and adds the necessary
prefix.

See also @hakonhagland comment in #2.

Closes #2

2021-11-22 09:50 UTC, rurban requested changes
This patch is worse than the other patches. The fixup is only needed for the macOS system perl, where they don't have the headers in archlibexp

2021-11-22 19:55 UTC, nega0 commented
This, like the "other patches" is better than any patch you've provided since this was first brought to your attention in December 2020.

Since you're requesting changes, what specifically would you like to see?

2021-11-22 22:14 UTC, rurban commented
Eg the RT ticket uses 
```
   if ($^O eq "darwin" && $Config{archlibexp} =~ m!^/System/Library/Perl!) {
```

2021-11-22 22:52 UTC, nega0 commented
Hi @rurban! Sorry it took so long, work got in the way (always gets in the way amirite :grin: ?), but I found some time to expand the check for `keywords.h`. We load it now from a subroutine that uses a small list of our preferred locations. This will make it easy to expand in the future, or if `Config.pm` ever gets updated the list will always be correct. Works just great with Homebrew `perl` too! 

Here's a quick run down

```~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ make clean > /dev/null

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ which perl
/usr/bin/perl

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ perl Makefile.PL && make
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for B::Keywords
Writing MYMETA.yml and MYMETA.json
cp lib/B/Keywords.pm blib/lib/B/Keywords.pm
Manifying 1 pod document

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/10basic.t ................. ok
t/11keywords.t .............. ok
t/export.t .................. ok
t/z_kwalitee.t .............. skipped: Text::CSV_XS required for Test::Kwalitee
t/z_meta.t .................. skipped: Test::CPAN::Meta 0.12 not available for testing
t/z_perl_minimum_version.t .. skipped: Perl::MinimumVersion 1.20 not available for testing
t/z_pod-coverage.t .......... skipped: Test::Pod::Coverage 1.04 required for testing POD coverage
t/z_pod.t ................... ok
All tests successful.
Files=8, Tests=548,  1 wallclock secs ( 0.07 usr  0.02 sys +  0.56 cusr  0.20 csys =  0.85 CPU)
Result: PASS

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ brew install perl
==> Downloading https://ghcr.io/v2/homebrew/core/perl/manifests/5.34.0
Already downloaded: /Users/nega/Library/Caches/Homebrew/downloads/73a7c7ed1f6227f886206df5fdfbb99018db085f96be5e9feea51d86817fc8c3--perl-5.34.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/perl/blobs/sha256:5f86afbccd065524f92080bd7f35ffe6398b7dd40a8fef6f0a2a7982fd276dae
Already downloaded: /Users/nega/Library/Caches/Homebrew/downloads/a8ae70cad6a3eefb9284f96676f8351cdc26b0d6b7bbc2fac79f45f2e16709ab--perl--5.34.0.big_sur.bottle.tar.gz
==> Pouring perl--5.34.0.big_sur.bottle.tar.gz
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.zshrc
==> Summary
🍺  /usr/local/Cellar/perl/5.34.0: 2,482 files, 66.8MB

~/Downloads/b-keywords nega/keyword_test_fix* ⇡ 13s
❯ brew --prefix
/usr/local

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ rehash

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ which perl
/usr/local/bin/perl

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ make clean > /dev/null

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ perl Makefile.PL && make
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for B::Keywords
Writing MYMETA.yml and MYMETA.json
cp lib/B/Keywords.pm blib/lib/B/Keywords.pm
Manifying 1 pod document
utf8 mode requested but Encode module not available, falling back to non-utf8 at /Users/nega/perl5/lib/perl5/ExtUtils/Command/MM.pm line 151.

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ make test
PERL_DL_NONLAZY=1 "/usr/local/Cellar/perl/5.34.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/10basic.t ................. ok
t/11keywords.t .............. ok
t/export.t .................. ok
t/z_kwalitee.t .............. skipped: Class::XSAccessor required for Test::Kwalitee
t/z_meta.t .................. skipped: Test::CPAN::Meta 0.12 not available for testing
t/z_perl_minimum_version.t .. skipped: Perl::MinimumVersion 1.20 not available for testing
t/z_pod-coverage.t .......... skipped: Test::Pod::Coverage 1.04 required for testing POD coverage
t/z_pod.t ................... skipped: Test::Pod 1.00 required for testing POD
All tests successful.
Files=8, Tests=553,  1 wallclock secs ( 0.07 usr  0.02 sys +  0.49 cusr  0.15 csys =  0.73 CPU)
Result: PASS

~/Downloads/b-keywords nega/keyword_test_fix* ⇡
❯ 
```

I don't have access to a different OS at the moment, mostly because it's time to leave the office, but I assume you do and can take care of further testing. Anyway, happy coding!

2022-02-21 09:00 UTC, rurban approved these changes
Looks good now, thanks

2022-02-21 09:01 UTC, merged